### ISSUE TITLE
Revisit state syntax

### ISSUE THREAD

**Issue by merlinz01** [merlinz01/redpepper#69]
The current state syntax works well, but has these drawbacks:

- You can't set an explicit label for a state, you have to use a comment.
- The built-in parameters `type`, `if`, and `onchange` are parallel with operation arguments. Which brings backward-compatibility concerns.

Better:
```yaml
name: Foo the bar
type: command.Run
args:
    command: cat foo | bar --stdin
    user: baz
if:
    ...
onchange:
    ...
```
